### ISSUE TITLE
Empty box after registration

### ISSUE THREAD

**Issue by MagnusErler** [DurgNomis-drol/ha_toyota#254]
**Describe the bug**
When adding the integration, and typing in the email and password for the MyToyota app, a blank box pops up and nothing happens

**To Reproduce**
1. Go to settings - Devices and services - Add integration - _search for_ "Toyota Connected Services"
2. Type in your email and password for MyToyota app
3. Box shows up with no additional information

**Expected behavior**
No empty box

**Screenshots**
![Screenshot from 2024-04-09 19-48-51](https://github.com/DurgNomis-drol/ha_toyota/assets/32124450/f7e757d0-ac05-4de8-96c9-3ac9272a28f1)

**Additional context**
No information in the logs

**Comment by CM000n** [comment]
Probably you are also affected by this: https://github.com/DurgNomis-drol/ha_toyota/issues/248 ?

**Comment by MagnusErler** [comment]
Could be. However is there no integration-card. It just seems like the integration failed and couldn't be added.

**Comment by CM000n** [comment]
Could you enable debug logging for the integration and see if you get any helpful logs (load full state logs)?

**Comment by MagnusErler** [comment]
How would I do that? The integration is not installed.

The only thing I see is the login box (see picture below) and then the empty box after clicking submit
![Screenshot from 2024-04-10 20-12-52](https://github.com/DurgNomis-drol/ha_toyota/assets/32124450/52f174bf-fc86-4791-b2d7-6f034873dbeb)

**Comment by CM000n** [comment]
The logging settings are independent of the integration itself.
These are made in the `logger` config: https://www.home-assistant.io/integrations/logger/

For example, my logger config looks like this:
```yaml
---
# https://www.home-assistant.io/integrations/logger
logger:
  default: "error"
  logs:
    homeassistant.components.vicare: "critical"
    custom_components.toyota: "debug"
```

**Comment by MagnusErler** [comment]
Thank you for clarifying.
I added the following to my configuration.yaml

```
logger:
  default: warning
  logs:
    custom_components.toyota: debug
```

Restarted HA and tried to add the integration (resulting in an empty box).
However didn't find anything in the logs about the integration... (I assume "debug" is the lowest level of logging)
